---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/geekstso/public_html/hotelsys/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R crud-design-html $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp error_log $DEPLOYPATH
